#!/usr/bin/python

import urllib2
from HTMLParser import HTMLParser
import random

# create a subclass and override the handler methods
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
    	if tag == 'a':
       		if attrs[0][1] == 'image-list-link':
       			url = attrs[1][1]
       			img_id = url.split('/')[-1]
       			#img_url = 'http://i.imgur.com/' + img_id + '.jpg'
       			img_url = 'http://i.imgur.com/removed.png'
			img_urls.append(img_url)

# instantiate the parser and fed it some HTML
parser = MyHTMLParser()

subreddit = "pics"
source_url = "http://imgur.com/r/" + subreddit + "/"
img_urls = [] #list of images in subreddit (hopefully not gifs)

response = urllib2.urlopen('http://imgur.com/r/pics/')
html = response.read()
parser.feed(html)

# Randomly select image from list
#image_url = random.choice(img_urls)
image_url = 'http://i.imgur.com/removed.png'
print 'downloading image : ' + image_url

# Download the image at url
resource = urllib2.urlopen(image_url)
img_file = open("invalid.png","wb")
img_file.write(resource.read())
img_file.close()
