#!/usr/bin/python
# -*- coding: UTF-8 -*-

#!/usr/bin/python

import smtplib
import urllib, cStringIO
from PIL import Image

sender = 'jared.weinstein@fromdomain.com'
receivers = ['3035798796@vtext.com']

message = """From: From Person <gongon595@gmail.com>
To: To Person <to@todomain.com>
Subject: SMTP e-mail test

This is a test e-mail message.
"""
URL = "http://i805.photobucket.com/albums/yy336/jessegillz/fuck-you2.jpg"
file = cStringIO.StringIO(urllib.urlopen(URL).read())
img = Image.open(file)

try:
   smtpObj = smtplib.SMTP('localhost')
   smtpObj.sendmail(sender, receivers, message)
   smtpObj.attach(img)
   print "Successfully sent email"
except SMTPException:
   print "Error: unable to send email"
