#!/usr/bin/python
# -*- coding: UTF-8 -*-

#!/usr/bin/python

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart


def SendMail(ImgFileName):
    #img_data = open(ImgFileName, 'rb').read()
    msg = MIMEMultipart()
    msg['Subject'] = 'subject'
    msg['From'] = 'e@mail.cc'
    msg['To'] = '3037184216@mms.att.net'

    text = MIMEText("test")
    msg.attach(text)
    #image = MIMEImage(img_data, name=os.path.basename(ImgFileName))
    #msg.attach(image)

    s = smtplib.SMTP(Server, Port)
    s.ehlo()
    s.starttls()
    s.ehlo()
    s.login('soccerstar199@gmail.com', 'jb1rdjb1rd')
    s.sendmail(From, To, msg.as_string())
    s.quit()


SendMail("http://i805.photobucket.com/albums/yy336/jessegillz/fuck-you2.jpg")
