#!/usr/bin/python
# smspython.py
# Sends sms message to any cell phone using gmail smtp gateway
# Written by Alex Le (http://alexanderle.com)

import smtplib, base64, sys, re

from email.MIMEMultipart import MIMEMultipart
from email.MIMEText import MIMEText
from email.MIMEImage import MIMEImage

MAX_TEXT_LENGTH = 160

SmsGateways = [
   'mms.att.net',             # at&t
   'sms.att.net'
]

def LogInSMTPServer( email, password ):
   server = smtplib.SMTP( "smtp.gmail.com", 587 )
   server.starttls()
   server.login( email, password )

   return server

def SendSMS( server, phone, msg_text, attach_file ):

   if len( msg_text ) <= MAX_TEXT_LENGTH:

      # Send to all gateways, since a phone number
      # can only be specific to one carrier.
      for gateway in SmsGateways:
         destination = phone + '@' + gateway

         msg = MIMEMultipart()
         msg.attach( MIMEText(msg_text, 'plain') )

         # Check if valid attachment
         if attach_file != '':
            fp = open( attach_file, 'rb' )
            msg_img = MIMEImage( fp.read() )
            fp.close()

            msg.attach( msg_img )

         server.sendmail( '', destination, msg.as_string() )

   else:
      print 'Message is too long. SMS not sent.'

   server.quit()

#### Main Program ####
fo = open( 'sms_info.txt', 'r' )

# Read sensitive information from external file
email = 'soccerstar199@gmail.com'
password = 'jb1rdjb1rd'

p = re.compile( '\d{10}' )

# Get destination phone number
phone = '3037184216'

# Get message
msg_text = "newscript"

# Ask for attachments
attach_file = raw_input( 'Enter attachments: ')

print '\nLogging into SMTP server..'
smtp_server = LogInSMTPServer( email, password )

SendSMS( smtp_server, phone, msg_text, attach_file )
print 'SMS sent to %s' % phone
